### ISSUE TITLE
Add template code samples

### ISSUE THREAD

**Issue by putyourlightson** [putyourlightson/craft-cp-style-guide#2]
Currently, you need to look at the plugin's template files to see how to use Craft's native fields with twig code. It would be great to be able to view the twig code inside the plugin's control panel pages. This requires some front-end work to make it possible to view the code in a usable, unobtrusive way.

**Comment by boscho87** [comment]
i suggest to use
https://highlightjs.org/static/demo/

**Comment by bencroker** [comment]
Closing, as this plugin is no longer getting updates.
