### ISSUE TITLE
Error : Impossible to invoke a method ("format") on a string variable ("Nov 30, 2018").

### ISSUE THREAD

**Issue by onemoreahmad** [putyourlightson/craft-cp-style-guide#3]
Hello,

I got this error when I first install the plugin
craft version 3.0.33

Thanks

<img width="1624" alt="screen shot 2018-12-01 at 3 28 28 am" src="https://user-images.githubusercontent.com/1885785/49321572-41b26d00-f519-11e8-9493-0b16bd89b0e0.png">

**Comment by putyourlightson** [comment]
I just tested a fresh install on Craft 3.0.33 and can't replicate your error. Any other clues?

**Comment by onemoreahmad** [comment]
Umm, I have no idea really, I just checked my composer and I notice it's 
"craftcms/cms": "dev-develop as 3.0.33", but I think it's the same isn't it? 
BTW this issue is exactly in both plugins **CP Style Guide** and **Plugin UXD**.

Thank you

**Comment by putyourlightson** [comment]
Just released 1.0.2, please try it and let me know if it works.

**Comment by onemoreahmad** [comment]
Thanks a lot, works now!

**Comment by putyourlightson** [comment]
Great!
